name: Flask CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: |
          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/todo_project
          python -m unittest discover -s todo_project/tests -p "test_*.py"

      - name: Bandit - Análise Estática de Código
        run: |
          pip install bandit
          bandit -r todo_project --exit-zero

      - name: Criar diretório de relatório
        run: mkdir -p reports

      - name: OWASP Dependency-Check - Análise de Dependências
        run: |
          mkdir -p reports
          docker pull owasp/dependency-check
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/reports:/report \
            owasp/dependency-check \
            --project "FlaskApp" \
            --scan /src \
            --format "HTML" \
            --out /report

      - name: Upload do relatório de dependências
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

